/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MVCViews;

import MVCControllers.*;
import MVCModels.ClientSearchResult;
import MVCModels.currentBooking;
import java.awt.BorderLayout;
import java.awt.Container;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Time;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class BTB_View extends javax.swing.JFrame {

    String result; // holds return value

    //controller transmits information between BTB view and BTB controller
    private BTB_Controller controller = new BTB_Controller();
    private DefaultTableModel model = new DefaultTableModel();
    private DefaultTableModel modelAdmin = new DefaultTableModel();

    //Clean object that is going to be used to 'purify' user Input and clear textfields
    Clean clean = new Clean();

    /**
     * Creates new form BTB_View
     */
    public BTB_View() throws SQLException {
        initComponents();
        jMenuBar.setVisible(false);
        this.getContentPane().removeAll();
        //defaultWelcomePanel.setVisible(true);
        this.add(defaultWelcomePanel, BorderLayout.CENTER);
        this.repaint();
        this.pack();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        DialogPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bookingTripOrigin = new javax.swing.JLabel();
        bookingTripDestination = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        bookingVehicleNumber = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        bookingAvailableSeats = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        bookingDateOfTrip = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        bookingTripDepartureTime = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        BookingTripFare = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        bookingClientFirstNameTextField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        bookingClientLastNameTextField = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        bookingClientIDTextField = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        bookingClientNumberOfSeatsTextField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        bookingBookSeatButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        defaultWelcomePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        clientSearchTripButton = new javax.swing.JButton();
        tripOriginSearchComboBox = new javax.swing.JComboBox<>();
        tripDestinationSearchComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchResultsTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        jLabel4 = new javax.swing.JLabel();
        goToAdminLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        TripTravelDateDateChooser = new com.toedter.calendar.JDateChooser();
        adminWelcomePanel = new javax.swing.JPanel();
        bookASeatLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        currentBookingsTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        addVehiclePanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        vehicleNumberTextField = new javax.swing.JTextField();
        vehicleNumberOfSeatsTextField = new javax.swing.JTextField();
        vehicleAddButton = new javax.swing.JButton();
        vehicleAddResetButton = new javax.swing.JButton();
        addTripPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tripOriginTextField = new javax.swing.JTextField();
        tripDestinationTextField = new javax.swing.JTextField();
        addTripButton = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        tripFareTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        departureTimeComboBox = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        addTripVehicleComboBox = new javax.swing.JComboBox<>();
        jMenuBar = new javax.swing.JMenuBar();
        manageVehiclesMenu = new javax.swing.JMenu();
        addVehicleMenuItem = new javax.swing.JMenuItem();
        updateVehicleMenuItem = new javax.swing.JMenuItem();
        viewVehiclesMenuItem = new javax.swing.JMenuItem();
        deleteVehiclesMenuItem = new javax.swing.JMenuItem();
        manageTripsMenu = new javax.swing.JMenu();
        addTripMenuItem = new javax.swing.JMenuItem();
        updateTripMenuItem = new javax.swing.JMenuItem();
        viewTripsMenuItem = new javax.swing.JMenuItem();
        cancelTripMenuItem = new javax.swing.JMenuItem();
        BookingsMenu = new javax.swing.JMenu();
        viewBookingsMenuItem = new javax.swing.JMenuItem();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setTitle("BOOK A SEAT");
        jDialog1.setResizable(false);
        jDialog1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDialog1WindowOpened(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("TRIP DETAILS");

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel7.setText("Origin :");

        bookingTripOrigin.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        bookingTripOrigin.setText("Origin");

        bookingTripDestination.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        bookingTripDestination.setText("Origin");

        jLabel21.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel21.setText("Destination : ");

        bookingVehicleNumber.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        bookingVehicleNumber.setText("Origin");

        jLabel23.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel23.setText("Vehicle Number : ");

        bookingAvailableSeats.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        bookingAvailableSeats.setText("Origin");

        jLabel25.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel25.setText("Available Seats :");

        bookingDateOfTrip.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        bookingDateOfTrip.setText("Origin");

        jLabel27.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel27.setText("Date of Trip : ");

        bookingTripDepartureTime.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        bookingTripDepartureTime.setText("Origin");

        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel29.setText("Departure Time :");

        BookingTripFare.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        BookingTripFare.setText("Origin");

        jLabel31.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel31.setText("Trip Fare (FCFA) : ");

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel32.setText("CLIENT DETAILS");

        bookingClientFirstNameTextField.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jLabel34.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel34.setText("Last Name : ");

        bookingClientLastNameTextField.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jLabel35.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel35.setText("ID CARD No: ");

        bookingClientIDTextField.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        jLabel36.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel36.setText("Book : ");

        bookingClientNumberOfSeatsTextField.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        jLabel37.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jLabel37.setText("seat(s)");

        bookingBookSeatButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        bookingBookSeatButton.setText("BOOK SEAT");
        bookingBookSeatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingBookSeatButtonActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton5.setText("CANCEL");

        jLabel38.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel38.setText("First Name :");

        javax.swing.GroupLayout DialogPanelLayout = new javax.swing.GroupLayout(DialogPanel);
        DialogPanel.setLayout(DialogPanelLayout);
        DialogPanelLayout.setHorizontalGroup(
            DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogPanelLayout.createSequentialGroup()
                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DialogPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel7)
                            .addComponent(jLabel27)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DialogPanelLayout.createSequentialGroup()
                                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bookingDateOfTrip, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bookingVehicleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bookingTripOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel29))
                                .addGap(18, 18, 18)
                                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bookingTripDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bookingAvailableSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bookingTripDepartureTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BookingTripFare)))
                    .addGroup(DialogPanelLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel5)))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DialogPanelLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DialogPanelLayout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(bookingBookSeatButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                            .addComponent(jButton5)
                            .addGap(106, 106, 106))
                        .addGroup(DialogPanelLayout.createSequentialGroup()
                            .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(DialogPanelLayout.createSequentialGroup()
                                    .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(DialogPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel35)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(bookingClientIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(DialogPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel38)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bookingClientFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)
                                    .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(DialogPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel34)
                                            .addGap(18, 18, 18)
                                            .addComponent(bookingClientLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(DialogPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel36)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(bookingClientNumberOfSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel37))))
                                .addGroup(DialogPanelLayout.createSequentialGroup()
                                    .addGap(221, 221, 221)
                                    .addComponent(jLabel32)))
                            .addGap(41, 41, 41)))))
        );
        DialogPanelLayout.setVerticalGroup(
            DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(bookingTripDestination)
                    .addComponent(bookingTripOrigin)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(bookingAvailableSeats)
                    .addComponent(bookingVehicleNumber)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(bookingTripDepartureTime)
                    .addComponent(bookingDateOfTrip)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookingTripFare)
                    .addComponent(jLabel31))
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DialogPanelLayout.createSequentialGroup()
                    .addGap(189, 189, 189)
                    .addComponent(jLabel32)
                    .addGap(18, 18, 18)
                    .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bookingClientFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34)
                        .addComponent(bookingClientLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel38))
                    .addGap(18, 18, 18)
                    .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bookingClientNumberOfSeatsTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                        .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(bookingClientIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36)
                            .addComponent(jLabel37)))
                    .addGap(47, 47, 47)
                    .addGroup(DialogPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bookingBookSeatButton)
                        .addComponent(jButton5))
                    .addContainerGap()))
        );

        jDialog1.getContentPane().add(DialogPanel, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BTB - Bus Ticket Booking");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setText("Source : ");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Book a Seat for a Trip");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("Destination : ");

        clientSearchTripButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        clientSearchTripButton.setText("Search");
        clientSearchTripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientSearchTripButtonActionPerformed(evt);
            }
        });

        tripOriginSearchComboBox.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        tripOriginSearchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        tripOriginSearchComboBox.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tripOriginSearchComboBoxAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        tripDestinationSearchComboBox.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        tripDestinationSearchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        searchResultsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        searchResultsTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                searchResultsTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        searchResultsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchResultsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(searchResultsTable);

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText("Date of Travel : ");

        goToAdminLabel.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        goToAdminLabel.setText("ADMIN");
        goToAdminLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToAdminLabelMouseClicked(evt);
            }
        });

        jLabel6.setText("Tip: Click on a search result to book a seat");

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TripTravelDateDateChooser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TripTravelDateDateChooserAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TripTravelDateDateChooser.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                TripTravelDateDateChooserComponentMoved(evt);
            }
        });

        javax.swing.GroupLayout defaultWelcomePanelLayout = new javax.swing.GroupLayout(defaultWelcomePanel);
        defaultWelcomePanel.setLayout(defaultWelcomePanelLayout);
        defaultWelcomePanelLayout.setHorizontalGroup(
            defaultWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultWelcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(defaultWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultWelcomePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultWelcomePanelLayout.createSequentialGroup()
                        .addGroup(defaultWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(defaultWelcomePanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tripOriginSearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tripDestinationSearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(defaultWelcomePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2)))
                        .addGap(23, 23, 23)
                        .addGroup(defaultWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(defaultWelcomePanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TripTravelDateDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(clientSearchTripButton)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultWelcomePanelLayout.createSequentialGroup()
                                .addComponent(goToAdminLabel)
                                .addContainerGap())))
                    .addGroup(defaultWelcomePanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(defaultWelcomePanelLayout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        defaultWelcomePanelLayout.setVerticalGroup(
            defaultWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultWelcomePanelLayout.createSequentialGroup()
                .addGroup(defaultWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(defaultWelcomePanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2))
                    .addGroup(defaultWelcomePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(goToAdminLabel)))
                .addGap(33, 33, 33)
                .addGroup(defaultWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(defaultWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(clientSearchTripButton)
                        .addComponent(tripOriginSearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tripDestinationSearchComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(TripTravelDateDateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        getContentPane().add(defaultWelcomePanel, java.awt.BorderLayout.CENTER);

        bookASeatLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        bookASeatLabel.setText("Book a Seat");
        bookASeatLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookASeatLabelMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel8.setText("Welcome Admin");

        currentBookingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        currentBookingsTable.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                currentBookingsTableAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(currentBookingsTable);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setText("Current Bookings");

        jButton3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton3.setText("Print");

        jButton4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminWelcomePanelLayout = new javax.swing.GroupLayout(adminWelcomePanel);
        adminWelcomePanel.setLayout(adminWelcomePanelLayout);
        adminWelcomePanelLayout.setHorizontalGroup(
            adminWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminWelcomePanelLayout.createSequentialGroup()
                .addGroup(adminWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminWelcomePanelLayout.createSequentialGroup()
                        .addGroup(adminWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminWelcomePanelLayout.createSequentialGroup()
                                .addGap(333, 333, 333)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adminWelcomePanelLayout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addComponent(jLabel8)))
                        .addGap(0, 286, Short.MAX_VALUE))
                    .addGroup(adminWelcomePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(adminWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminWelcomePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bookASeatLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adminWelcomePanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        adminWelcomePanelLayout.setVerticalGroup(
            adminWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminWelcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bookASeatLabel)
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addGroup(adminWelcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        getContentPane().add(adminWelcomePanel, java.awt.BorderLayout.PAGE_START);

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel15.setText("Add Vehicle Details");

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setText("Number of Seats : ");

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setText("Vehicle Number : ");

        vehicleNumberTextField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        vehicleNumberOfSeatsTextField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        vehicleAddButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        vehicleAddButton.setText("ADD");
        vehicleAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleAddButtonActionPerformed(evt);
            }
        });

        vehicleAddResetButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        vehicleAddResetButton.setText("RESET");

        javax.swing.GroupLayout addVehiclePanelLayout = new javax.swing.GroupLayout(addVehiclePanel);
        addVehiclePanel.setLayout(addVehiclePanelLayout);
        addVehiclePanelLayout.setHorizontalGroup(
            addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addVehiclePanelLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addGroup(addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addVehiclePanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel15)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addVehiclePanelLayout.createSequentialGroup()
                        .addGroup(addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(addVehiclePanelLayout.createSequentialGroup()
                                .addComponent(vehicleAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vehicleAddResetButton))
                            .addGroup(addVehiclePanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addVehiclePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addVehiclePanelLayout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)))
                                .addGroup(addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vehicleNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehicleNumberOfSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(199, Short.MAX_VALUE))))
        );
        addVehiclePanelLayout.setVerticalGroup(
            addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addVehiclePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleNumberOfSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleAddButton)
                    .addComponent(vehicleAddResetButton))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        getContentPane().add(addVehiclePanel, java.awt.BorderLayout.LINE_END);

        addTripPanel.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                addTripPanelComponentAdded(evt);
            }
        });
        addTripPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addTripPanelFocusGained(evt);
            }
        });
        addTripPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                addTripPanelComponentShown(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setText("Add Trip Details");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setText("Trip Destination : ");

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setText("Trip Source (Origin) : ");

        tripOriginTextField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tripOriginTextField.setText("jTextField1");

        tripDestinationTextField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tripDestinationTextField.setText("jTextField1");

        addTripButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addTripButton.setText("ADD");
        addTripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTripButtonActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton6.setText("RESET");
        jButton6.setName(""); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setText("Fare : ");

        tripFareTextField.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tripFareTextField.setText("jTextField1");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setText("Departure Time :");

        departureTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06:00", "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        departureTimeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departureTimeComboBoxActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setText("Vehicle Involved :");

        addTripVehicleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addTripVehicleComboBox.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                addTripVehicleComboBoxComponentAdded(evt);
            }
        });
        addTripVehicleComboBox.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                addTripVehicleComboBoxAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        addTripVehicleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTripVehicleComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addTripPanelLayout = new javax.swing.GroupLayout(addTripPanel);
        addTripPanel.setLayout(addTripPanelLayout);
        addTripPanelLayout.setHorizontalGroup(
            addTripPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTripPanelLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(addTripPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addTripPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(addTripPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tripOriginTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(departureTimeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addTripButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTripVehicleComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(addTripPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTripPanelLayout.createSequentialGroup()
                        .addGroup(addTripPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addTripPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tripFareTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(tripDestinationTextField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addTripPanelLayout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        addTripPanelLayout.setVerticalGroup(
            addTripPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addTripPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(addTripPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tripOriginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tripDestinationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addTripPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tripFareTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departureTimeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addTripPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTripVehicleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(addTripPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTripButton)
                    .addComponent(jButton6))
                .addGap(25, 25, 25))
        );

        getContentPane().add(addTripPanel, java.awt.BorderLayout.PAGE_END);

        jMenuBar.setName(""); // NOI18N

        manageVehiclesMenu.setText("Manage Vehicles");
        manageVehiclesMenu.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        addVehicleMenuItem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        addVehicleMenuItem.setText("Add a Vehicle");
        addVehicleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVehicleMenuItemActionPerformed(evt);
            }
        });
        manageVehiclesMenu.add(addVehicleMenuItem);

        updateVehicleMenuItem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        updateVehicleMenuItem.setText("Update Vehicle Details");
        manageVehiclesMenu.add(updateVehicleMenuItem);

        viewVehiclesMenuItem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        viewVehiclesMenuItem.setText("View All Vehicles");
        manageVehiclesMenu.add(viewVehiclesMenuItem);

        deleteVehiclesMenuItem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        deleteVehiclesMenuItem.setText("Delete a Vehicle");
        manageVehiclesMenu.add(deleteVehiclesMenuItem);

        jMenuBar.add(manageVehiclesMenu);

        manageTripsMenu.setText("Manage Trips");
        manageTripsMenu.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        manageTripsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTripsMenuActionPerformed(evt);
            }
        });

        addTripMenuItem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        addTripMenuItem.setText("Add a Trip");
        addTripMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTripMenuItemActionPerformed(evt);
            }
        });
        manageTripsMenu.add(addTripMenuItem);

        updateTripMenuItem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        updateTripMenuItem.setText("Update Trip Details");
        manageTripsMenu.add(updateTripMenuItem);

        viewTripsMenuItem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        viewTripsMenuItem.setText("View Planned Trips");
        manageTripsMenu.add(viewTripsMenuItem);

        cancelTripMenuItem.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cancelTripMenuItem.setText("Cancel a Trip");
        manageTripsMenu.add(cancelTripMenuItem);

        jMenuBar.add(manageTripsMenu);

        BookingsMenu.setText("Bookings");
        BookingsMenu.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        BookingsMenu.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                BookingsMenuMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        BookingsMenu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                BookingsMenuStateChanged(evt);
            }
        });
        BookingsMenu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                BookingsMenuMenuSelected(evt);
            }
        });
        BookingsMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookingsMenuMouseClicked(evt);
            }
        });
        BookingsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingsMenuActionPerformed(evt);
            }
        });

        viewBookingsMenuItem.setText("View Bookings");
        viewBookingsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBookingsMenuItemActionPerformed(evt);
            }
        });
        BookingsMenu.add(viewBookingsMenuItem);

        jMenuBar.add(BookingsMenu);

        setJMenuBar(jMenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addVehicleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVehicleMenuItemActionPerformed
        // TODO add your handling code here:
        Container c = getContentPane();
        c.removeAll();
        addVehiclePanel.setVisible(true);
        c.add(addVehiclePanel, BorderLayout.CENTER);
        this.repaint();
        this.pack();
    }//GEN-LAST:event_addVehicleMenuItemActionPerformed

    private void addTripMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTripMenuItemActionPerformed
        // TODO add your handling code here:
        Container c = getContentPane();
        c.removeAll();
        addTripPanel.setVisible(true);
        c.add(addTripPanel, BorderLayout.CENTER);
        this.repaint();
        this.pack();
    }//GEN-LAST:event_addTripMenuItemActionPerformed

    private void BookingsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingsMenuActionPerformed
        // TODO add your handling code here:
        Container c = getContentPane();
        c.removeAll();
        adminWelcomePanel.setVisible(true);
        c.add(adminWelcomePanel, BorderLayout.CENTER);
        this.repaint();
        this.pack();
    }//GEN-LAST:event_BookingsMenuActionPerformed

    private void manageTripsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTripsMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageTripsMenuActionPerformed

    private void goToAdminLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToAdminLabelMouseClicked
        // TODO add your handling code here:
        Container c = getContentPane();
        c.removeAll();
        adminWelcomePanel.setVisible(true);
        c.add(adminWelcomePanel, BorderLayout.CENTER);
        jMenuBar.setVisible(true);
        this.repaint();
        this.pack();
    }//GEN-LAST:event_goToAdminLabelMouseClicked

    private void BookingsMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookingsMenuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingsMenuMouseClicked

    private void BookingsMenuMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_BookingsMenuMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingsMenuMenuSelected

    private void BookingsMenuMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_BookingsMenuMenuKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_BookingsMenuMenuKeyPressed

    private void BookingsMenuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_BookingsMenuStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_BookingsMenuStateChanged

    private void viewBookingsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBookingsMenuItemActionPerformed
        // TODO add your handling code here:
        Container c = getContentPane();
        c.removeAll();
        adminWelcomePanel.setVisible(true);
        c.add(adminWelcomePanel, BorderLayout.CENTER);
        jMenuBar.setVisible(true);
        this.repaint();
        this.pack();

    }//GEN-LAST:event_viewBookingsMenuItemActionPerformed

    private void vehicleAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleAddButtonActionPerformed
        // TODO add your handling code here:
        String vehicleNumber = vehicleNumberTextField.getText();
        int vehicleNumberOfSeats = Integer.parseInt(vehicleNumberOfSeatsTextField.getText());

        result = controller.addVehicle(vehicleNumber, vehicleNumberOfSeats);

        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_vehicleAddButtonActionPerformed

    private void addTripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTripButtonActionPerformed
        // TODO add your handling code here:
        String tripOrigin = tripOriginTextField.getText();
        String tripDestination = tripDestinationTextField.getText();
        int tripFare = Integer.parseInt(tripFareTextField.getText());
        String selectedTime = (String) departureTimeComboBox.getSelectedItem() + ":00";

        Time departTime = java.sql.Time.valueOf(selectedTime);

        result = controller.addTrip(tripOrigin, tripDestination, tripFare, departTime, addTripVehicleComboBox.getSelectedItem().toString());
        JOptionPane.showMessageDialog(null, result);

    }//GEN-LAST:event_addTripButtonActionPerformed

    private void departureTimeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departureTimeComboBoxActionPerformed
        // TODO add your handling code here:
        //converting selected time to SQL understandable time

    }//GEN-LAST:event_departureTimeComboBoxActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        clean.resetTextFields(addTripPanel);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void addTripVehicleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTripVehicleComboBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_addTripVehicleComboBoxActionPerformed

    private void addTripPanelComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_addTripPanelComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_addTripPanelComponentAdded

    private void addTripPanelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addTripPanelFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_addTripPanelFocusGained

    private void addTripPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_addTripPanelComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_addTripPanelComponentShown

    private void addTripVehicleComboBoxComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_addTripVehicleComboBoxComponentAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_addTripVehicleComboBoxComponentAdded

    private void addTripVehicleComboBoxAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_addTripVehicleComboBoxAncestorAdded
        // TODO add your handling code here:
        String[] result = controller.getAllVehicles(); //holds list of vehicle id numbers

        //first clear jcombobox contents
        addTripVehicleComboBox.removeAllItems();

        //populate Jcombobox items with identity number of vehicles
        for (int i = 0; i < result.length; i++) {
            addTripVehicleComboBox.addItem(result[i]);
        }
    }//GEN-LAST:event_addTripVehicleComboBoxAncestorAdded

    private void currentBookingsTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_currentBookingsTableAncestorAdded
        // TODO add your handling code here:
        Object[] columnTitles = new Object[7];
        
        columnTitles[0] = "Passenger ID";
        columnTitles[1] = "Passenger F. Name";
        columnTitles[2] = "Passenger L. Name";
        columnTitles[3] = "Trip Origin";
        columnTitles[4] = "Trip Destination";
        columnTitles[5] = "Trip Fare";
        columnTitles[6] = "Date of Travel";
        
        modelAdmin.setColumnIdentifiers(columnTitles);
        currentBookingsTable.setModel(modelAdmin);
       // currentBookingsTable.setAutoResizeMode(currentBookingsTable.AUTO_RESIZE_ALL_COLUMNS);
       
       //display table values
       //a row object to hold wor values
       Object[] tablerows = new Object[7];
       
       ArrayList <currentBooking> currentBookingsList = new ArrayList<>();
       currentBookingsList = controller.getCurrentBookings();
       
       //Clear all rows to add new ones
       modelAdmin.setRowCount(0);
        for(int i = 0; i < currentBookingsList.size(); i++){
                tablerows[0] = currentBookingsList.get(i).getClientIdentityNumber();
                tablerows[1] = currentBookingsList.get(i).getClientFirstName();
                tablerows[2] = currentBookingsList.get(i).getClientLastName();
                tablerows[3] = currentBookingsList.get(i).getTripOrigin();
                tablerows[4] = currentBookingsList.get(i).getTripDestination();
                tablerows[5] = currentBookingsList.get(i).getTripFare();
                tablerows[6] = currentBookingsList.get(i).getTripDate();
                
                modelAdmin.addRow(tablerows);
        }
    }//GEN-LAST:event_currentBookingsTableAncestorAdded

    private void clientSearchTripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientSearchTripButtonActionPerformed
        // TODO add your handling code here:

        //Get values that are going to be used as parameters for the search
        String tripOrigin, tripDestination;

        tripOrigin = tripOriginSearchComboBox.getSelectedItem().toString();
        tripDestination = tripDestinationSearchComboBox.getSelectedItem().toString();
        
        //get values that will go into JTable
        Object[] tablerows = new Object[4];
       
        //get values from controller
        ArrayList <ClientSearchResult> searchResults = new ArrayList<>();
        searchResults = controller.getUserSearchResults(tripOrigin, tripDestination);
        
        ClientSearchResult searchResult = new ClientSearchResult(); 
        model.setRowCount(0);
        for (int i = 0; i < searchResults.size(); i++){
            //get one instance of the search results and pass into the ClientSearchResult object which is used
            //to facilitate getting the results
            searchResult = searchResults.get(i);
            
            tablerows[0] = searchResult.getBusIdentityNumber();
            tablerows[1] = searchResult.getBusNumberOfAvailableSeats();
            tablerows[2] = searchResult.getTripDepartureTime();
            tablerows[3] = searchResult.getTripFare();
            
            model.addRow(tablerows);
        }
        
        //if no result, display Error message
        if(model.getRowCount() == 0)
            JOptionPane.showMessageDialog(null, "No trips to that destination have been programmed yet \n Check later");
        
        searchResultsTable.setModel(model);
    }//GEN-LAST:event_clientSearchTripButtonActionPerformed

    private void tripOriginSearchComboBoxAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tripOriginSearchComboBoxAncestorAdded
        // TODO add your handling code here:
        String[] result = controller.getAllTripOrigins();

        //first clear jcombobox contents
        tripOriginSearchComboBox.removeAllItems();
        tripDestinationSearchComboBox.removeAllItems();

        //populate Jcombobox items with identity number of vehicles
        for (int i = 0; i < result.length; i++) {
            tripOriginSearchComboBox.addItem(result[i]);
        }

        result = null;
        result = controller.getAllTripDestinations();

        //populate Jcombobox items with identity number of vehicles
        for (int i = 0; i < result.length; i++) {
            tripDestinationSearchComboBox.addItem(result[i]);
        }
    }//GEN-LAST:event_tripOriginSearchComboBoxAncestorAdded

    private void bookASeatLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookASeatLabelMouseClicked
        // TODO add your handling code here:
        Container c = getContentPane();
        c.removeAll();
        defaultWelcomePanel.setVisible(true);
        c.add(defaultWelcomePanel, BorderLayout.CENTER);
        jMenuBar.setVisible(false);
        this.repaint();
        this.pack();
    }//GEN-LAST:event_bookASeatLabelMouseClicked

    private void searchResultsTableAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_searchResultsTableAncestorAdded
        // TODO add your handling code here:
        Object[] columnTitles = new Object[4];
        
        columnTitles[0] = "VEHICLE NUMBER";
        columnTitles[1] = "AVAILABLE NUMBER OF SEATS";
        columnTitles[2] = "DEPARTURE TIME";
        columnTitles[3] = "TRIP FARE";
        
        model.setColumnIdentifiers(columnTitles);
         searchResultsTable.setModel(model);
    }//GEN-LAST:event_searchResultsTableAncestorAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
       System.exit(0);  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchResultsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchResultsTableMouseClicked
        // TODO add your handling code here:
        
        //the values from the selected row, set them in the JDialog, and display the Dialog
        int index = searchResultsTable.getSelectedRow();
        
        //collecting table values
        bookingVehicleNumber.setText(searchResultsTable.getValueAt(index, 0).toString());
        bookingAvailableSeats.setText(searchResultsTable.getValueAt(index, 1).toString());
        bookingTripDepartureTime.setText(searchResultsTable.getValueAt(index, 2).toString());
        BookingTripFare.setText(searchResultsTable.getValueAt(index, 3).toString());
        
        //collecting other values
        bookingTripOrigin.setText(tripOriginSearchComboBox.getSelectedItem().toString());
        bookingTripDestination.setText(tripDestinationSearchComboBox.getSelectedItem().toString());
        
        
//        String dateFormat = "yyyy-mm-dd";
//        TripTravelDateDateChooser.setDateFormatString(dateFormat); //put the date in the format required

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String strDate = sdf.format(TripTravelDateDateChooser.getDate());
        
        //for the date, first we get the date with TripTravelDateDateChooser.getDate()
        //then format the Date value to a String
        //String strDate = DateFormat.getDateInstance().format(TripTravelDateDateChooser.getDate());
        
        //set the value into as text for the label
        bookingDateOfTrip.setText(strDate);
        
        //Display the Dialog
        jDialog1.getContentPane().add(DialogPanel,BorderLayout.CENTER);
        jDialog1.pack();
        jDialog1.setVisible(true);
        jDialog1.setLocationRelativeTo(null);
    }//GEN-LAST:event_searchResultsTableMouseClicked

    private void TripTravelDateDateChooserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TripTravelDateDateChooserAncestorAdded
        // TODO add your handling code here:
        //Date format
        String dateFormat = "yyyy-MM-dd";
        TripTravelDateDateChooser.setMinSelectableDate(new Date());
        TripTravelDateDateChooser.setDate(new Date());
        TripTravelDateDateChooser.setDateFormatString(dateFormat);
    }//GEN-LAST:event_TripTravelDateDateChooserAncestorAdded

    private void jDialog1WindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDialog1WindowOpened

    }//GEN-LAST:event_jDialog1WindowOpened

    private void bookingBookSeatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingBookSeatButtonActionPerformed
        // TODO add your handling code here:
        String clientFirstName = bookingClientFirstNameTextField.getText();
        String clientLastName = bookingClientLastNameTextField.getText();
        int clientIDCardNumber = Integer.parseInt(bookingClientIDTextField.getText());
        int numberOfSeatsBooked = Integer.parseInt(bookingClientNumberOfSeatsTextField.getText());
        String tripOrigin = bookingTripOrigin.getText();
        String tripDestination = bookingTripDestination.getText();
        String tripDate = bookingDateOfTrip.getText();
        
        try {
            result = controller.bookTrip(clientIDCardNumber, clientFirstName, clientLastName, tripOrigin, 
                                                tripDestination, tripDate, numberOfSeatsBooked);
        } catch (ParseException ex) {
            Logger.getLogger(BTB_View.class.getName()).log(Level.SEVERE, null, ex);
        }
        //controller.addClient(clientIDCardNumber, clientFirstName, clientLastName);
        JOptionPane.showMessageDialog(null, result);
    }//GEN-LAST:event_bookingBookSeatButtonActionPerformed

    private void TripTravelDateDateChooserComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TripTravelDateDateChooserComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TripTravelDateDateChooserComponentMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BTB_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BTB_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BTB_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BTB_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BTB_View().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(BTB_View.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BookingTripFare;
    private javax.swing.JMenu BookingsMenu;
    private javax.swing.JPanel DialogPanel;
    private com.toedter.calendar.JDateChooser TripTravelDateDateChooser;
    private javax.swing.JButton addTripButton;
    private javax.swing.JMenuItem addTripMenuItem;
    private javax.swing.JPanel addTripPanel;
    private javax.swing.JComboBox<String> addTripVehicleComboBox;
    private javax.swing.JMenuItem addVehicleMenuItem;
    private javax.swing.JPanel addVehiclePanel;
    private javax.swing.JPanel adminWelcomePanel;
    private javax.swing.JLabel bookASeatLabel;
    private javax.swing.JLabel bookingAvailableSeats;
    private javax.swing.JButton bookingBookSeatButton;
    private javax.swing.JTextField bookingClientFirstNameTextField;
    private javax.swing.JTextField bookingClientIDTextField;
    private javax.swing.JTextField bookingClientLastNameTextField;
    private javax.swing.JTextField bookingClientNumberOfSeatsTextField;
    private javax.swing.JLabel bookingDateOfTrip;
    private javax.swing.JLabel bookingTripDepartureTime;
    private javax.swing.JLabel bookingTripDestination;
    private javax.swing.JLabel bookingTripOrigin;
    private javax.swing.JLabel bookingVehicleNumber;
    private javax.swing.JMenuItem cancelTripMenuItem;
    private javax.swing.JButton clientSearchTripButton;
    private javax.swing.JTable currentBookingsTable;
    private javax.swing.JPanel defaultWelcomePanel;
    private javax.swing.JMenuItem deleteVehiclesMenuItem;
    private javax.swing.JComboBox<String> departureTimeComboBox;
    private javax.swing.JLabel goToAdminLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu manageTripsMenu;
    private javax.swing.JMenu manageVehiclesMenu;
    private javax.swing.JTable searchResultsTable;
    private javax.swing.JComboBox<String> tripDestinationSearchComboBox;
    private javax.swing.JTextField tripDestinationTextField;
    private javax.swing.JTextField tripFareTextField;
    private javax.swing.JComboBox<String> tripOriginSearchComboBox;
    private javax.swing.JTextField tripOriginTextField;
    private javax.swing.JMenuItem updateTripMenuItem;
    private javax.swing.JMenuItem updateVehicleMenuItem;
    private javax.swing.JButton vehicleAddButton;
    private javax.swing.JButton vehicleAddResetButton;
    private javax.swing.JTextField vehicleNumberOfSeatsTextField;
    private javax.swing.JTextField vehicleNumberTextField;
    private javax.swing.JMenuItem viewBookingsMenuItem;
    private javax.swing.JMenuItem viewTripsMenuItem;
    private javax.swing.JMenuItem viewVehiclesMenuItem;
    // End of variables declaration//GEN-END:variables
}
